version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    image: aliceicelie/devops-for-programmers-project-74
  development:
    build:
      context: .
      dockerfile: Dockerfile
